kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: java21-s2i
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'java21-s2i:latest'
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  source:
    type: Git
    git:
      uri: 'https://github.com/relessawy/kotlin_demo'
      ref: main
    contextDir: Chapter10/guestbook